FilelibDemoBundle:
    resource: "@FilelibDemoBundle/Resources/config/routing.yml"
    prefix:   /

FilelibBundle:
    resource: "@FilelibBundle/Resources/config/routing.yml"
    prefix: /filelib

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
