parameters:
#    filelib_demo.example.class: Filelib\Bundle\DemoBundle\Example

services:
#    filelib_demo.example:
#        class: %filelib_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
